# Generated by Django 3.1.4 on 2021-01-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url_path', models.CharField(max_length=200)),
                ('productset_group_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('list_price', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
                ('rating_count', models.IntegerField()),
                ('rating_total', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('shop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('logo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sell_product', serialize=False, to='tiki.product')),
                ('min_qty', models.IntegerField()),
                ('max_qty', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'sell',
                'managed': False,
            },
        ),
    ]
