# Generated by Django 3.1.4 on 2021-01-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiki', '0002_auto_20210111_0611'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='sell',
            table='sell',
        ),
    ]
